import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jasmineguglielmi
 */
public class ClientsForm extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form ClientsForm
     */
    public ClientsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCreditcard = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClients = new javax.swing.JTable();
        jButtonEdit = new javax.swing.JButton();
        jButtonClearFields = new javax.swing.JButton();
        jButtonAddClient = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jTextFieldLastname = new javax.swing.JTextField();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 221, 29));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clients Portfolio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel2.setText("First name:");

        jLabel3.setText("Last name:");

        jLabel4.setText("Contact n°:");

        jLabel5.setText("E-mail:");

        jLabel6.setText("Credit card n°:");

        jTableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
               
            },
            new String [] {
                "First name", "Last name", "Contact n°", "Email", "Creditcard", "Total amount"
            }
        ) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			@SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClients.getTableHeader().setReorderingAllowed(false);
        jTableClients.setColumnSelectionAllowed(false);
        jTableClients.setSelectionBackground(new java.awt.Color(255, 255, 153));
        jTableClients.setShowGrid(true);
        jTableClients.setGridColor(new java.awt.Color(255, 255, 153));
        jScrollPane1.setViewportView(jTableClients);
        jTableClients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientsMouseClicked(evt);
            }					
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonClearFields.setForeground(new java.awt.Color(255, 51, 0));
        jButtonClearFields.setText("Clear Fields");
        jButtonClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFieldsActionPerformed(evt);
            }
        });

        jButtonAddClient.setText("Add new Client");
        jButtonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientActionPerformed(evt);
            }
        });

        jButtonRefresh.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(51, 255, 204));
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new ActionListener() {			
			@Override
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				jButtonRefreshActionPerformed(evt);				
			}		
		});

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldCreditcard, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldLastname)))
                    .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCreditcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
        cl.fillClientsJTable(jTableClients);
    }// </editor-fold>                        

    private void jButtonAddClientActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    	if (jTextFieldFirstName.getText().trim().isEmpty()) 
			JOptionPane.showMessageDialog(this, "Campo \"First Name\" obbligatorio");
		else if (jTextFieldLastname.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"Last Name\" obbligatorio");
		else if (jTextFieldNumber.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"Contact Number\" obbligatorio");
		else if (jTextFieldEmail.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"E-mail\" obbligatorio");
		else if (jTextFieldCreditcard.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"Credit Card\" obbligatorio");
		else {
			cl.setFirst_name(jTextFieldFirstName.getText());
			cl.setLast_name(jTextFieldLastname.getText());
			cl.setContact_number(jTextFieldNumber.getText());
			cl.setE_mail(jTextFieldEmail.getText());
			cl.setCredit_card(jTextFieldCreditcard.getText());
			//System.out.println("item selected" + jComboBoxType.getSelectedItem());
			if(cl.addClient()) {
				JOptionPane.showMessageDialog(this, "Operation Success", "Information Panel", JOptionPane.INFORMATION_MESSAGE);
			}
			else
				JOptionPane.showMessageDialog(this, "Client already exixts", "Error Panel", JOptionPane.ERROR_MESSAGE);
		}
    }                                                

    
    private void jButtonRefreshActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	DefaultTableModel def = (DefaultTableModel)jTableClients.getModel();
		//System.out.println("numero righe" + def.getRowCount());
		int n = def.getRowCount();
		for(int i = 0; i < n; i++)    		
			def.removeRow(0);
		cl.fillClientsJTable(jTableClients);
	}
    
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:  
    	if (jTextFieldFirstName.getText().trim().isEmpty()) 
			JOptionPane.showMessageDialog(this, "Compulsory field \"First Name\"");
		else if (jTextFieldLastname.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Compulsory field \"Last Name\"");
		else if (jTextFieldNumber.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Compulsory field \"Contact Number\"");
		else if (jTextFieldEmail.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Compulsory field \"E-mail\"");
		else if (jTextFieldCreditcard.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Compulsory field \"Credit Card\"");
		else {
			cl.setFirst_name((String) jTableClients.getValueAt(jTableClients.getSelectedRow(), 0));
			cl.setLast_name((String) jTableClients.getValueAt(jTableClients.getSelectedRow(), 1));
			//cl.setContact_number(jTextFieldNumber.getText());
			cl.setE_mail((String) jTableClients.getValueAt(jTableClients.getSelectedRow(), 3));
			//cl.setCredit_card(jTextFieldCreditcard.getText());
			//System.out.println("item selected" + jComboBoxType.getSelectedItem());
			if(cl.editClients(jTextFieldFirstName.getText(), jTextFieldLastname.getText(), jTextFieldEmail.getText(), jTextFieldNumber.getText(), jTextFieldCreditcard.getText())) {
				JOptionPane.showMessageDialog(this, "Operation Success", "Information Panel", JOptionPane.INFORMATION_MESSAGE);
			}
			else
				JOptionPane.showMessageDialog(this, "Operation Error", "Error Panel", JOptionPane.ERROR_MESSAGE);
			cl.setFirst_name(null);
			cl.setLast_name(null);
			cl.setE_mail(null);
			cl.setContact_number(null);
			cl.setCredit_card(null);
		}
    }                                           

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	if (jTextFieldFirstName.getText().trim().isEmpty()) 
			JOptionPane.showMessageDialog(this, "Campo \"First Name\" obbligatorio");
		else if (jTextFieldLastname.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"Last Name\" obbligatorio");
		else if (jTextFieldEmail.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"E-mail\" obbligatorio");
		else {
			cl.setFirst_name(jTextFieldFirstName.getText());
			cl.setLast_name(jTextFieldLastname.getText());
			cl.setE_mail(jTextFieldEmail.getText());
			//System.out.println("item selected" + jComboBoxType.getSelectedItem());
			if(cl.removeClients()) {
				JOptionPane.showMessageDialog(this, "Operation Success", "Information Panel", JOptionPane.INFORMATION_MESSAGE);
			}
			else
				JOptionPane.showMessageDialog(this, "Operation Error", "Error Panel", JOptionPane.ERROR_MESSAGE);
		}
    }                                             

    private void jButtonClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       jTextFieldFirstName.setText("");
       jTextFieldLastname.setText("");
       jTextFieldEmail.setText("");
       jTextFieldNumber.setText("");
       jTextFieldCreditcard.setText("");
    }                                       
    
    private void jTableClientsMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	DefaultTableModel def = (DefaultTableModel)jTableClients.getModel();
		//System.out.println((boolean)def.getValueAt(jTableRooms.getSelectedRow(), 4));
  
        jTextFieldFirstName.setText(def.getValueAt(jTableClients.getSelectedRow(), 0).toString());
        jTextFieldLastname.setText((String) def.getValueAt(jTableClients.getSelectedRow(), 1));
        jTextFieldNumber.setText((String) def.getValueAt(jTableClients.getSelectedRow(), 2));
        jTextFieldEmail.setText((String) def.getValueAt(jTableClients.getSelectedRow(), 3));
        jTextFieldCreditcard.setText((String) def.getValueAt(jTableClients.getSelectedRow(), 4));  
 
	}	

   

    // Variables declaration - do not modify    
    private Client cl = new Client();
    private javax.swing.JButton jButtonAddClient;
    private javax.swing.JButton jButtonClearFields;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClients;
    private javax.swing.JTextField jTextFieldCreditcard;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldNumber;
    // End of variables declaration                   
}
