import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jasmineguglielmi
 */
@SuppressWarnings("unused")
public class LoginForm extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form LoginForm
	 */
	public LoginForm() {
		initComponents();
		this.setLocationRelativeTo(null);
	//	this.move
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	 // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextFieldClose = new javax.swing.JTextField();
        jTextFieldShowMin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jButtonCancel = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabelNewAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 153, 102));
        jTextField3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Login Form");
        jTextField3.setBorder(null);
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextFieldClose.setEditable(false);
        jTextFieldClose.setBackground(new java.awt.Color(255, 153, 102));
        jTextFieldClose.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldClose.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldClose.setText("X");
        jTextFieldClose.setBorder(null);
        jTextFieldClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextFieldClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCloseMouseClicked(evt);
            }
        });
        jTextFieldClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCloseActionPerformed(evt);
            }
        });

        jTextFieldShowMin.setEditable(false);
        jTextFieldShowMin.setBackground(new java.awt.Color(255, 153, 102));
        jTextFieldShowMin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTextFieldShowMin.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldShowMin.setText("_");
        jTextFieldShowMin.setBorder(null);
        jTextFieldShowMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextFieldShowMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldShowMinMouseClicked(evt);
            }
        });
        jTextFieldShowMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShowMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldShowMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldShowMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 205, 255));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Password:");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField.setEditable(false);
        jTextField.setBackground(new java.awt.Color(102, 205, 255));
        jTextField.setForeground(new java.awt.Color(255, 255, 255));
        jTextField.setText("Username:");
        jTextField.setBorder(null);
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jCheckBoxShowPass.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jCheckBoxShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setBackground(new java.awt.Color(102, 204, 255));
        jCheckBoxShowPass.setText("Show pass");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 102, 102));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 204, 102));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jLabelNewAccount.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabelNewAccount.setText("New user? Click here to create an account.");
        jLabelNewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNewAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxShowPass))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelNewAccount))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxShowPass)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNewAccount)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        
// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jTextField1ActionPerformed

	private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jTextFieldActionPerformed

	private void jTextFieldShowMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShowMinActionPerformed

	}//GEN-LAST:event_jTextFieldShowMinActionPerformed

	private void jTextFieldCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCloseActionPerformed

	}//GEN-LAST:event_jTextFieldCloseActionPerformed

	private void jTextFieldCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCloseMouseClicked
		System.exit(0);
	}//GEN-LAST:event_jTextFieldCloseMouseClicked

	private void jTextFieldShowMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldShowMinMouseClicked
		this.setState(JFrame.ICONIFIED);
	}//GEN-LAST:event_jTextFieldShowMinMouseClicked

	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
		// TODO add your handling code here:
		/*System.out.println(evt.getActionCommand());
		log.setPassword(evt.getActionCommand());*/
	}//GEN-LAST:event_jPasswordField1ActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:

		//System.out.println(evt.getActionCommand());
		//log.setUsername(evt.getActionCommand());


	}//GEN-LAST:event_jTextField2ActionPerformed

	private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
		if(jCheckBoxShowPass.isSelected()){
			jPasswordField1.setEchoChar((char)0);
		}
		else {
			jPasswordField1.setEchoChar('•');
		}
	}//GEN-LAST:event_jCheckBoxShowPassActionPerformed

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		// TODO add your handling code here:
		jTextField2.setText("");
		jPasswordField1.setText("");
		
	}//GEN-LAST:event_jButtonCancelActionPerformed

	private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
		// TODO add your handling code here:
		//System.out.println(log.Username + "  " + log.Password);
		//System.out.println(jPasswordField1.getPassword());
		log.setPassword(new String(jPasswordField1.getPassword()));
		//System.out.println(jTextField2.getText());
		log.setUsername(jTextField2.getText());
		
		boolean res = log.verifica();
		//System.out.println(res);
		//se riesco ad effettuare il login devo settare tutti i campi di log a null 
		if (!res) {
			JOptionPane.showMessageDialog(this, "Access Denied", "ERROR", JOptionPane.ERROR_MESSAGE);   		
			/*
			 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
			 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
			 * ("Nimbus".equals(info.getName())) {
			 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
			 * (ClassNotFoundException ex) {
			 * java.util.logging.Logger.getLogger(NewOkCancelDialog.class.getName()).log(
			 * java.util.logging.Level.SEVERE, null, ex); } catch (InstantiationException
			 * ex) {
			 * java.util.logging.Logger.getLogger(NewOkCancelDialog.class.getName()).log(
			 * java.util.logging.Level.SEVERE, null, ex); } catch (IllegalAccessException
			 * ex) {
			 * java.util.logging.Logger.getLogger(NewOkCancelDialog.class.getName()).log(
			 * java.util.logging.Level.SEVERE, null, ex); } catch
			 * (javax.swing.UnsupportedLookAndFeelException ex) {
			 * java.util.logging.Logger.getLogger(NewOkCancelDialog.class.getName()).log(
			 * java.util.logging.Level.SEVERE, null, ex); }
			 */
			//</editor-fold>

			/* Create and display the dialog */
			/*
			 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
			 * NewOkCancelDialog dialog = new NewOkCancelDialog(new javax.swing.JFrame(),
			 * true); dialog.addWindowListener(new java.awt.event.WindowAdapter() {
			 * 
			 * @Override public void windowClosing(java.awt.event.WindowEvent e) {
			 * System.exit(0); } }); dialog.setVisible(true); } });
			 */
		}
		else {
			//System.out.println("ciao");
			log.setNull();
			MainForm2 mf= new MainForm2();
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
            //mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            this.dispose();
		}
		
		
	}
	//GEN-LAST:event_jButtonLoginActionPerformed

	private void jLabelNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewAccountMouseClicked
		signupForm supf = new signupForm();
		supf.setVisible(true);
		supf.pack();
		supf.setLocationRelativeTo(null);
		supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.dispose();
	}//GEN-LAST:event_jLabelNewAccountMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				System.out.println(info.getClassName());
				if ("WindowsClassic".equals(info.getName())) {
					System.out.println(info.getClassName());
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginForm().setVisible(true);
				//new Provaconnessione();
				//new Connection2();
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private Login log = new Login();
	private javax.swing.JButton jButtonCancel;
	private javax.swing.JButton jButtonLogin;
	private javax.swing.JCheckBox jCheckBoxShowPass;
	private javax.swing.JLabel jLabelNewAccount;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextFieldClose;
	private javax.swing.JTextField jTextFieldShowMin;
	// End of variables declaration//GEN-END:variables
}