/*
 * import java.awt.event.ActionEvent; import java.awt.event.ActionListener;
 * 
 * import javax.swing.ImageIcon; import javax.swing.JFrame; import
 * javax.swing.JLabel;
 * 
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 * 
 * 
 *//**
	 *
	 * @author jasmineguglielmi
	 */
/*
 * public class MainForm extends javax.swing.JFrame {
 * 
 *//**
	* 
	*/
/*
 * private static final long serialVersionUID = 1L;
 *//**
	 * Creates new form Management
	 */
/*
 * public MainForm() { initComponents(); }
 * 
 *//**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
/*
 * 
 * // <editor-fold defaultstate="collapsed" desc="Generated //
 * Code">//GEN-BEGIN:initComponents private void initComponents() {
 * 
 * jPanel2 = new javax.swing.JPanel(); jMenuBar1 = new javax.swing.JMenuBar();
 * jMenu1 = new javax.swing.JMenu(); jMenuRooms = new javax.swing.JMenuItem();
 * jSeparator1 = new javax.swing.JPopupMenu.Separator(); jMenuClients = new
 * javax.swing.JMenuItem(); jSeparator3 = new
 * javax.swing.JPopupMenu.Separator(); jMenuReservations = new
 * javax.swing.JMenuItem();
 * 
 * 
 * 
 * setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 * 
 * javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
 * jPanel2.setLayout(jPanel2Layout);
 * jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.
 * swing.GroupLayout.Alignment.LEADING) .addGap(0, 713, Short.MAX_VALUE));
 * jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.
 * GroupLayout.Alignment.LEADING) .addGap(0, 481, Short.MAX_VALUE));
 * 
 * jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
 * jMenuBar1.setBounds(new java.awt.Rectangle(10, 10, 86, 22));
 * 
 * jMenu1.setText("Manage >"); jMenu1.setFont(new java.awt.Font("Lucida Grande",
 * 1, 18)); // NOI18N
 * 
 * jMenuRooms.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
 * jMenuRooms.setText("Rooms"); jMenuRooms.addMouseListener(new
 * java.awt.event.MouseAdapter() { public void
 * mouseClicked(java.awt.event.MouseEvent evt) { jMenuRoomsMouseClicked(evt); }
 * });
 * 
 * jMenuRooms.addActionListener(new java.awt.event.ActionListener() { public
 * void actionPerformed(java.awt.event.ActionEvent evt) {
 * jMenuRoomsActionPerformed(evt); } }); jMenu1.add(jMenuRooms);
 * jMenu1.add(jSeparator1);
 * 
 * jMenuClients.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
 * jMenuClients.setText("Clients"); jMenuClients.addMouseListener(new
 * java.awt.event.MouseAdapter() { public void
 * mouseClicked(java.awt.event.MouseEvent evt) { //
 * jMenuClientsMouseClicked(evt); } }); jMenuClients.addActionListener(new
 * java.awt.event.ActionListener() { public void
 * actionPerformed(java.awt.event.ActionEvent evt) {
 * jMenuClientsActionPerformed(evt); } }); jMenu1.add(jMenuClients);
 * jMenu1.add(jSeparator3);
 * 
 * jMenuReservations.setFont(new java.awt.Font("Lucida Grande", 0, 18)); //
 * NOI18N jMenuReservations.setText("Reservations");
 * jMenuReservations.addMouseListener(new java.awt.event.MouseAdapter() { public
 * void mouseClicked(java.awt.event.MouseEvent evt) { //
 * jMenuReservationsMouseClicked(evt); } });
 * 
 * jMenuReservations.addActionListener(new ActionListener() {
 * 
 * @Override public void actionPerformed(ActionEvent e) {
 * jMenuReservationsActionPerformed(e); } }); jMenu1.add(jMenuReservations);
 * 
 * jMenuBar1.add(jMenu1);
 * 
 * setJMenuBar(jMenuBar1);
 * 
 * javax.swing.GroupLayout layout = new
 * javax.swing.GroupLayout(getContentPane());
 * getContentPane().setLayout(layout);
 * layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.
 * Alignment.LEADING).addComponent( jPanel2,
 * javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
 * Short.MAX_VALUE));
 * layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.
 * Alignment.LEADING).addComponent( jPanel2,
 * javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
 * Short.MAX_VALUE));
 * 
 * pack(); }// </editor-fold>//GEN-END:initComponents
 * 
 * private void jMenuRoomsActionPerformed(java.awt.event.ActionEvent evt) {//
 * GEN-FIRST:event_jMenuRoomsActionPerformed RoomsForm rf = new RoomsForm();
 * rf.setVisible(true); rf.pack(); rf.setLocationRelativeTo(null);
 * rf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); }//
 * GEN-LAST:event_jMenuRoomsActionPerformed
 * 
 * private void jMenuRoomsMouseClicked(java.awt.event.MouseEvent evt) {//
 * GEN-FIRST:event_jMenuRoomsMouseClicked RoomsForm rf = new RoomsForm();
 * rf.setVisible(true); rf.pack(); rf.setLocationRelativeTo(null);
 * rf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); }//
 * GEN-LAST:event_jMenuRoomsMouseClicked
 * 
 * private void jMenuClientsActionPerformed(java.awt.event.ActionEvent evt) {//
 * GEN-FIRST:event_jMenuClientsActionPerformed // TODO add your handling code
 * here: ClientsForm clf = new ClientsForm(); clf.setVisible(true); clf.pack();
 * clf.setLocationRelativeTo(null);
 * clf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); }//
 * GEN-LAST:event_jMenuClientsActionPerformed
 * 
 * private void jMenuReservationsActionPerformed(ActionEvent e) { // TODO
 * Auto-generated method stub ReservationForm rform = new ReservationForm();
 * rform.setVisible(true); rform.pack(); rform.setLocationRelativeTo(null);
 * rform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); }
 * 
 * private void jMenuClientsMouseClicked(java.awt.event.MouseEvent evt)
 * {//GEN-FIRST:event_jMenuClientsMouseClicked ClientsForm cf= new
 * ClientsForm(); cf.setVisible(true); cf.pack();
 * cf.setLocationRelativeTo(null);
 * cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 * }//GEN-LAST:event_jMenuClientsMouseClicked
 * 
 * 
 * private void jMenuReservationsMouseClicked(java.awt.event.MouseEvent evt)
 * {//GEN-FIRST:event_jMenuReservationsMouseClicked ReservationForm resf= new
 * ReservationForm(); resf.setVisible(true); resf.pack();
 * resf.setLocationRelativeTo(null);
 * resf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 * }//GEN-LAST:event_jMenuReservationsMouseClicked
 * 
 *//**
	 * @param args the command line arguments
	 *//*
		 * 
		 * public static void main(String args[]) {
		 * 
		 * Set the Nimbus look and feel //<editor-fold defaultstate="collapsed"
		 * desc=" Look and feel setting code (optional) "> If Nimbus (introduced in Java
		 * SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 * 
		 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
		 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
		 * ("Nimbus".equals(info.getName())) {
		 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
		 * (ClassNotFoundException ex) {
		 * java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch (InstantiationException ex) {
		 * java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch (IllegalAccessException ex) {
		 * java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch
		 * (javax.swing.UnsupportedLookAndFeelException ex) {
		 * java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } //</editor-fold> //</editor-fold>
		 * 
		 * Create and display the form java.awt.EventQueue.invokeLater(new Runnable() {
		 * public void run() { new MainForm().setVisible(true); } });
		 * 
		 * }
		 * 
		 * 
		 * // Variables declaration - do not modify//GEN-BEGIN:variables private JLabel
		 * sfondo = new JLabel(new ImageIcon("C:\\Users\\pales\\OneDrive\\Desktop"));
		 * private javax.swing.JMenu jMenu1; private javax.swing.JMenuBar jMenuBar1;
		 * private javax.swing.JMenuItem jMenuClients; private javax.swing.JMenuItem
		 * jMenuReservations; private javax.swing.JMenuItem jMenuRooms; private
		 * javax.swing.JPanel jPanel2; private javax.swing.JPopupMenu.Separator
		 * jSeparator1; private javax.swing.JPopupMenu.Separator jSeparator3; // End of
		 * variables declaration//GEN-END:variables }
		 */