
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jasmineguglielmi
 */
public class RoomsForm extends javax.swing.JFrame {

	/**
	 * Creates new form RoomsForm
	 */
	public RoomsForm() {
		initComponents();

		/*
		 * ButtonGroup bg= new ButtonGroup(); bg.add(jRadioButtonYes);
		 * bg.add(jRadioButtonNo);
		 */
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableRooms = new javax.swing.JTable();
		jButtonRefresh = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		//jLabel4 = new javax.swing.JLabel();
		jTextFieldNumberID = new javax.swing.JTextField();
		jButtonAddRoom = new javax.swing.JButton();
		jButtonEdit = new javax.swing.JButton();
		jButtonRemove = new javax.swing.JButton();
		jButtonClearFields = new javax.swing.JButton();
		jComboBoxType = new javax.swing.JComboBox<>();
		jLabel5 = new javax.swing.JLabel();
		jTextFieldPhone = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		//jRadioButtonYes = new javax.swing.JRadioButton();
		//jRadioButtonNo = new javax.swing.JRadioButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(51, 0, 255));

		jLabel1.setBackground(new java.awt.Color(51, 51, 255));
		jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Manage Rooms");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(34, 34, 34)
						.addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(26, 26, 26)
						.addComponent(jLabel1)
						.addContainerGap(29, Short.MAX_VALUE))
				);

		jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jTableRooms.setRowSelectionAllowed(true);
        jTableRooms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableRooms.setShowGrid(true);
        jTableRooms.getTableHeader().setReorderingAllowed(false);
        jTableRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }			
        });
		jTableRooms.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {

				},
				new String [] {
						"Number ID", "Type", "Price per day", "Phone", "Reserved"
				}
				) {
			Class[] types = new Class [] {
					java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
			};
			boolean[] canEdit = new boolean [] {
					false, false, false, false, false
			};

			public Class<?> getColumnClass(int columnIndex) {
				return types [columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit [columnIndex];
			}
		});
		jTableRooms.setColumnSelectionAllowed(false);
		jTableRooms.setSelectionBackground(new java.awt.Color(102, 255, 102));
        jTableRooms.setSelectionForeground(new java.awt.Color(153, 204, 0));
        jTableRooms.setGridColor(new java.awt.Color(0, 204, 255));
        jTableRooms.setSelectionBackground(new java.awt.Color(0, 153, 255));
		jScrollPane1.setViewportView(jTableRooms);
		jTableRooms.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		if (jTableRooms.getColumnModel().getColumnCount() > 0) {
			jTableRooms.getColumnModel().getColumn(0).setResizable(false);
			jTableRooms.getColumnModel().getColumn(1).setResizable(false);
			jTableRooms.getColumnModel().getColumn(2).setResizable(false);
			jTableRooms.getColumnModel().getColumn(3).setResizable(false);
			jTableRooms.getColumnModel().getColumn(4).setResizable(false);
		}

		jButtonRefresh.setBackground(new java.awt.Color(204, 255, 255));
		jButtonRefresh.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
		jButtonRefresh.setText("Refresh");
		jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRefreshActionPerformed(evt);
			}
		});

		jLabel2.setText("Number ID:");

		jLabel3.setText("Room Type:");

		//jLabel4.setText("Reservated:");

		jButtonAddRoom.setText("Add new room");
		jButtonAddRoom.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddRoomActionPerformed(evt);
			}
		});

		jButtonEdit.setText("Edit");
		jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEditActionPerformed(evt);
			}
		});

		jPanel1.addMouseListener(new MouseListener() {		
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				jTableRooms.clearSelection();
				jTextFieldNumberID.setEditable(true);
				
			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
		jPanel2.addMouseListener(new MouseListener() {		
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				jTableRooms.clearSelection();
				jTextFieldNumberID.setEditable(true);
				
			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
		jPanel3.addMouseListener(new MouseListener() {		
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				jTableRooms.clearSelection();
				jTextFieldNumberID.setEditable(true);
				
			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
		jButtonRemove.setText("Remove");
		jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRemoveActionPerformed(evt);
			}
		});

		jButtonClearFields.setBackground(new java.awt.Color(204, 51, 0));
		jButtonClearFields.setText("Clear Fields ");
		jButtonClearFields.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonClearFieldsActionPerformed(evt);
			}
		});

		jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Family", "Suite" }));
		jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxTypeActionPerformed(evt);
			}
		});

		jLabel5.setText("Phone number:");

		jPanel3.setBackground(new java.awt.Color(204, 204, 204));

		/*
		 * jRadioButtonYes.setText("Yes"); jRadioButtonYes.addActionListener(new
		 * java.awt.event.ActionListener() { public void
		 * actionPerformed(java.awt.event.ActionEvent evt) {
		 * jRadioButtonYesActionPerformed(evt); } });
		 */

		//jRadioButtonNo.setText("No");
		/*
		 * jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() { public
		 * void actionPerformed(java.awt.event.ActionEvent evt) {
		 * jRadioButtonNoActionPerformed(evt); } });
		 */

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						//.addComponent(jRadioButtonYes)
						.addGap(18, 18, 18)
						//.addComponent(jRadioButtonNo)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								//.addComponent(jRadioButtonYes)
								/*.addComponent(jRadioButtonNo)*/)
						.addContainerGap(10, Short.MAX_VALUE))
				);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addContainerGap()
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(jPanel2Layout.createSequentialGroup()
																		.addComponent(jLabel5)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jTextFieldPhone))
																.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
																		.addComponent(jButtonRemove)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jButtonEdit)
																		.addGap(25, 25, 25))))
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addContainerGap()
														.addComponent(jButtonClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addContainerGap()
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel3)
																.addGroup(jPanel2Layout.createSequentialGroup()
																		//.addComponent(jLabel4)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGap(0, 0, Short.MAX_VALUE))
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addGap(8, 8, 8)
														.addComponent(jLabel2)
														.addGap(32, 32, 32)
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextFieldNumberID)
																.addComponent(jComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGap(99, 99, 99)
										.addComponent(jButtonAddRoom)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
								.addComponent(jButtonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(17, 17, 17))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGap(59, 59, 59)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextFieldNumberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel2Layout.createSequentialGroup()
														.addGap(11, 11, 11)
														/* .addComponent(jLabel4) */))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
										.addComponent(jButtonAddRoom)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtonEdit)
												.addComponent(jButtonRemove)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonClearFields))
						.addContainerGap(127, Short.MAX_VALUE))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();        

		r.fillRoomJTable(jTableRooms);
		System.out.println("iiiiiiiii");
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jComboBoxTypeActionPerformed

	private void jButtonAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRoomActionPerformed
		// TODO add your handling code here:
		if (jTextFieldNumberID.getText().trim().isEmpty()) 
			JOptionPane.showMessageDialog(this, "Campo \"ID\" obbligatorio");
		else if (jTextFieldPhone.getText().trim().isEmpty())
			JOptionPane.showMessageDialog(this, "Campo \"Phone Number\" obbligatorio");
		/*
		 * else if (!jRadioButtonNo.isSelected() && !jRadioButtonYes.isSelected())
		 * JOptionPane.showMessageDialog(this, "Campo \"Reserved\" obbligatorio");
		 */
		else {
			r.setRoomID(Integer.parseInt(jTextFieldNumberID.getText()));
			r.setPhone(jTextFieldPhone.getText());	
			//System.out.println("item selected" + jComboBoxType.getSelectedItem());
			r.setRoomType((String)(jComboBoxType.getSelectedItem()));
			if(r.addRoom(this)) {
				JOptionPane.showMessageDialog(this, "Operation Success", "Information Panel", JOptionPane.INFORMATION_MESSAGE);
			}
			/*else
				JOptionPane.showMessageDialog(this, "Operation Error", "Error Panel", JOptionPane.ERROR_MESSAGE);
		*/}

	}//GEN-LAST:event_jButtonAddRoomActionPerformed

	private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
		// TODO add your handling code here:
		DefaultTableModel deft = (DefaultTableModel)jTableRooms.getModel();
		
		if (jTextFieldNumberID.getText().trim().isEmpty()) 
			JOptionPane.showMessageDialog(this, "Campo \"ID\" obbligatorio");
		else if((boolean) deft.getValueAt(jTableRooms.getSelectedRow(), 4))
			JOptionPane.showMessageDialog(this, "Error Room reserved");
		else {
			r.setRoomID(Integer.parseInt(jTextFieldNumberID.getText()));
			if(r.removeRoom()) {
				JOptionPane.showMessageDialog(this, "Operation Success", "Information Panel", JOptionPane.INFORMATION_MESSAGE);
			}
			else
				JOptionPane.showMessageDialog(this, "Operation Error", "Error Panel", JOptionPane.ERROR_MESSAGE);
		}
		
	}//GEN-LAST:event_jButtonRemoveActionPerformed

	private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
		// TODO add your handling code here:
		DefaultTableModel deft = (DefaultTableModel)jTableRooms.getModel();
		
		if (jTextFieldNumberID.getText().trim().isEmpty()) 
			JOptionPane.showMessageDialog(this, "Campo \"ID\" obbligatorio");
		
		/*
		 * else if (jTextFieldPhone.getText().trim().isEmpty())
		 * JOptionPane.showMessageDialog(this, "Campo \"Phone Number\" obbligatorio");
		 */
		else if((boolean) deft.getValueAt(jTableRooms.getSelectedRow(), 4))
			JOptionPane.showMessageDialog(this, "Error Room reserved");
		/*
		 * else if (!jRadioButtonNo.isSelected() && !jRadioButtonYes.isSelected())
		 * JOptionPane.showMessageDialog(this, "Campo \"Reserved\" obbligatorio");
		 */
		else {
			
			String s = (String)jComboBoxType.getSelectedItem();
			/*
			 * if(jRadioButtonYes.isSelected()) interr = true; else
			 * if(jRadioButtonNo.isSelected()) interr = false;
			 */
			System.out.println("stampa" + jTextFieldPhone.getText() + jTextFieldNumberID.getText());
			if(r.editRoom(Integer.parseInt(jTextFieldNumberID.getText()), s, jTextFieldPhone.getText())) {
				JOptionPane.showMessageDialog(this, "Operation Success", "Information Panel", JOptionPane.INFORMATION_MESSAGE);
			}
			else
				JOptionPane.showMessageDialog(this, "Operation Error", "Error Panel", JOptionPane.ERROR_MESSAGE);
			
			
		}
		
	}//GEN-LAST:event_jButtonEditActionPerformed

	private void jButtonClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFieldsActionPerformed
		// TODO add your handling code here:
		jTextFieldNumberID.setText("");
		jTextFieldPhone.setText("");		
	}//GEN-LAST:event_jButtonClearFieldsActionPerformed

	private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
		// TODO add your handling code here:
		
		jTextFieldNumberID.setEditable(true);
		DefaultTableModel def = (DefaultTableModel)jTableRooms.getModel();
		System.out.println("numero righe" + def.getRowCount());
		int n = def.getRowCount();
		for(int i = 0; i < n; i++)    		
			def.removeRow(0);
		r.fillRoomJTable(jTableRooms);
		//r.fillRoomJTable(jTableRooms);
	}//GEN-LAST:event_jButtonRefreshActionPerformed

	/*
	 * private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt)
	 * {//GEN-FIRST:event_jRadioButtonNoActionPerformed // TODO add your handling
	 * code here: }//GEN-LAST:event_jRadioButtonNoActionPerformed
	 */
	/*
	 * private void jRadioButtonYesActionPerformed(java.awt.event.ActionEvent evt)
	 * {//GEN-FIRST:event_jRadioButtonYesActionPerformed // TODO add your handling
	 * code here: }//GEN-LAST:event_jRadioButtonYesActionPerformed
	 */
	private void jTable2MouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
		jTextFieldNumberID.setEditable(false);
		DefaultTableModel def = (DefaultTableModel)jTableRooms.getModel();
		System.out.println((boolean)def.getValueAt(jTableRooms.getSelectedRow(), 4));
  
        jTextFieldNumberID.setText(def.getValueAt(jTableRooms.getSelectedRow(), 0).toString());
        jTextFieldPhone.setText((String) def.getValueAt(jTableRooms.getSelectedRow(), 3));
        jComboBoxType.setSelectedItem((String)def.getValueAt(jTableRooms.getSelectedRow(), 1));
   
		/*
		 * if((boolean)def.getValueAt(jTableRooms.getSelectedRow(), 4)) {
		 * jRadioButtonNo.setSelected(false); jRadioButtonYes.setSelected(true); }else {
		 * jRadioButtonYes.setSelected(false); jRadioButtonNo.setSelected(true); }
		 */
        
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private Rooms r = new Rooms();
	private javax.swing.JButton jButtonAddRoom;
	private javax.swing.JButton jButtonClearFields;
	private javax.swing.JButton jButtonEdit;
	private javax.swing.JButton jButtonRefresh;
	private javax.swing.JButton jButtonRemove;
	private javax.swing.JComboBox<String> jComboBoxType;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	//private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	//private javax.swing.JRadioButton jRadioButtonNo;
	//private javax.swing.JRadioButton jRadioButtonYes;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableRooms;
	private javax.swing.JTextField jTextFieldNumberID;
	private javax.swing.JTextField jTextFieldPhone;
	// End of variables declaration//GEN-END:variables
}
